# Generated by Django 5.1.6 on 2026-01-06 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='conclusion',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='sections',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
