# Generated by Django 5.1.6 on 2026-01-06 08:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_blog_conclusion_blog_sections'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='sections',
        ),
        migrations.CreateModel(
            name='BlogSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('order', models.PositiveIntegerField(default=1)),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='blogs.blog')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
