# Generated by Django 5.2.9 on 2026-01-02 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('price', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('VILLA', 'Villa'), ('PENTHOUSE', 'Penthouse')], max_length=50)),
                ('status', models.CharField(choices=[('FOR SELL', 'For Sell'), ('FOR RENT', 'For Rent')], max_length=50)),
                ('beds', models.IntegerField()),
                ('baths', models.IntegerField()),
                ('size', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='properties/')),
                ('is_off_plan', models.BooleanField(default=False)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
